# Generated by Django 6.1 on 2026-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observer', '0002_authorgroup_author_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=300)),
                ('institution', models.CharField(max_length=300)),
                ('expertise', models.CharField(blank=True, help_text='E.g., Geopolitics, Public Policy', max_length=300)),
                ('biography', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='editorial/')),
                ('photo_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
